version: '2.4'

services:

  mn-hello-ni:
  ### OCI DevOps Build Pipelines
  ### Don't forget to replace the tag after running the build pipeline
    image: phx.ocir.io/oracledeveloper/ssp-mn/mn-hello-ni:qjp4wll
#    restart: 
    mem_limit: 128m
    memswap_limit: 128m
    cpu_count: 4
    cpu_percent: 100
    cpus: 4
    container_name: mn-hello-ni
    command:
      - '-Xms64m'
      - '-Xmx64m'
    ports:
      - "8080:8080"
